# Generated by Django 5.2.1 on 2025-06-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='usuario',
                    name='telefone',
                    field=models.CharField(blank=True, max_length=20, null=True),
                ),
            ]
        ),
    ]