from django.core.management.base import BaseCommand
from cadastros.models import PlanoDeContas

class Command(BaseCommand):
    help = 'Popula a tabela plano_de_contas com plano simplificado e detalhado'

    def handle(self, *args, **options):
        dados = [
            # --- SIMPLIFICADO (tipofluxocaixa = 1) ---
            {'conta': '1',   'descricao': 'Ativos',               'tipofluxocaixa': 1},
            {'conta': '1.1', 'descricao': 'Caixa',                'tipofluxocaixa': 1},
            {'conta': '1.2', 'descricao': 'Investimentos',        'tipofluxocaixa': 1},
            {'conta': '1.3', 'descricao': 'Produtos para revenda','tipofluxocaixa': 1},
            {'conta': '2',   'descricao': 'Passivo',              'tipofluxocaixa': 1},
            {'conta': '2.1', 'descricao': 'Impostos',             'tipofluxocaixa': 1},
            {'conta': '2.2', 'descricao': 'Empréstimos',          'tipofluxocaixa': 1},
            {'conta': '2.3', 'descricao': 'Salários',             'tipofluxocaixa': 1},
            {'conta': '3',   'descricao': 'Saída de caixa',       'tipofluxocaixa': 1},
            {'conta': '3.1', 'descricao': 'Custos dos produtos ou serviços', 'tipofluxocaixa': 1},
            {'conta': '3.2', 'descricao': 'Despesas administrativas','tipofluxocaixa': 1},
            {'conta': '3.3', 'descricao': 'Despesas comerciais',   'tipofluxocaixa': 1},
            {'conta': '3.4', 'descricao': 'Despesas financeiras',  'tipofluxocaixa': 1},
            {'conta': '4',   'descricao': 'Entrada de caixa',      'tipofluxocaixa': 1},
            {'conta': '4.1', 'descricao': 'Faturamento',           'tipofluxocaixa': 1},
            {'conta': '4.2', 'descricao': 'Rendimentos de aplicações','tipofluxocaixa': 1},

            # --- DETALHADO (tipofluxocaixa = 2) ---
            {'conta': '1',     'descricao': 'Ativo',                  'tipofluxocaixa': 2},
            {'conta': '1.1',   'descricao': 'Ativo Circulante',       'tipofluxocaixa': 2},
            {'conta': '1.1.1', 'descricao': 'Disponível',             'tipofluxocaixa': 2},
            {'conta': '1.1.1.1', 'descricao': 'Caixa',                'tipofluxocaixa': 2},
            {'conta': '1.1.1.2', 'descricao': 'Movimentação na conta','tipofluxocaixa': 2},
            {'conta': '1.1.1.3', 'descricao': 'Aplicações financeiras','tipofluxocaixa': 2},
            {'conta': '1.1.2', 'descricao': 'Recebimentos',           'tipofluxocaixa': 2},
            {'conta': '1.1.2.1', 'descricao': 'Clientes',             'tipofluxocaixa': 2},
            {'conta': '1.1.2.2', 'descricao': 'Pagamentos a receber','tipofluxocaixa': 2},
            {'conta': '1.1.2.3', 'descricao': 'Ações da empresa',     'tipofluxocaixa': 2},
            {'conta': '1.1.2.4', 'descricao': 'Possíveis inadimplentes','tipofluxocaixa': 2},
            {'conta': '1.1.2.5', 'descricao': 'Empréstimos a receber','tipofluxocaixa': 2},
            {'conta': '1.1.2.6', 'descricao': 'Cheques em cobrança',   'tipofluxocaixa': 2},
            {'conta': '1.1.2.7', 'descricao': 'Adiantamentos Salariais','tipofluxocaixa': 2},
            {'conta': '1.1.3', 'descricao': 'Estoques',               'tipofluxocaixa': 2},
            {'conta': '1.1.3.1', 'descricao': 'Mercadorias para venda','tipofluxocaixa': 2},
            {'conta': '1.1.3.2', 'descricao': 'Produtos Finais',      'tipofluxocaixa': 2},
            {'conta': '1.1.3.3', 'descricao': 'Produtos em processo','tipofluxocaixa': 2},
            {'conta': '1.1.4', 'descricao': 'Despesas',               'tipofluxocaixa': 2},
            {'conta': '1.1.4.1', 'descricao': 'Produção',            'tipofluxocaixa': 2},
            {'conta': '1.1.5', 'descricao': 'Ativo não circulante',  'tipofluxocaixa': 2},
            {'conta': '1.1.5.1', 'descricao': 'Direitos a longo prazo','tipofluxocaixa': 2},
            {'conta': '1.1.5.1.1', 'descricao': 'Títulos a receber', 'tipofluxocaixa': 2},
            {'conta': '1.1.5.1.2', 'descricao': 'Fundo de reserva',  'tipofluxocaixa': 2},
            {'conta': '1.1.5.1.3', 'descricao': 'Consórcios',       'tipofluxocaixa': 2},
            {'conta': '1.1.5.1.4', 'descricao': 'Investimentos',    'tipofluxocaixa': 2},
            {'conta': '1.1.5.1.5', 'descricao': 'Participações em outras empresas','tipofluxocaixa': 2},
            {'conta': '1.1.5.2', 'descricao': 'Imobilizados',         'tipofluxocaixa': 2},
            {'conta': '1.1.5.2.1', 'descricao': 'Terrenos',          'tipofluxocaixa': 2},
            {'conta': '1.1.5.2.2', 'descricao': 'Edificadores',       'tipofluxocaixa': 2},
            {'conta': '1.1.5.2.3', 'descricao': 'Imóveis para renda', 'tipofluxocaixa': 2},
            {'conta': '1.1.5.2.4', 'descricao': 'Veículos',          'tipofluxocaixa': 2},
            {'conta': '1.1.5.2.5', 'descricao': 'Marcas e patentes', 'tipofluxocaixa': 2},
            {'conta': '1.1.5.3', 'descricao': 'Tecnologia',          'tipofluxocaixa': 2},
            {'conta': '1.1.5.3.1', 'descricao': 'Despesas com pesquisas', 'tipofluxocaixa': 2},
            {'conta': '1.1.5.3.2', 'descricao': 'Desenvolvimento de produtos', 'tipofluxocaixa': 2},
            {'conta': '1.1.5.3.3', 'descricao': 'Automação de processos na empresa', 'tipofluxocaixa': 2},
            {'conta': '2',     'descricao': 'Passivo',                'tipofluxocaixa': 2},
            {'conta': '2.1',   'descricao': 'Circulante',             'tipofluxocaixa': 2},
            {'conta': '2.1.1', 'descricao': 'Obrigações fiscais',     'tipofluxocaixa': 2},
            {'conta': '2.1.1.1', 'descricao': 'ICMS',                 'tipofluxocaixa': 2},
            {'conta': '2.1.1.2', 'descricao': 'ISS',                  'tipofluxocaixa': 2},
            {'conta': '2.1.1.3', 'descricao': 'INSS',                 'tipofluxocaixa': 2},
            {'conta': '2.1.1.4', 'descricao': 'Cofins',               'tipofluxocaixa': 2},
            {'conta': '2.1.1.5', 'descricao': 'IRPJ',                 'tipofluxocaixa': 2},
            {'conta': '2.1.1.6', 'descricao': 'CSLL',                 'tipofluxocaixa': 2},
            {'conta': '2.1.1.7', 'descricao': 'CPP',                  'tipofluxocaixa': 2},
            {'conta': '2.1.2', 'descricao': 'Contas a pagar',        'tipofluxocaixa': 2},
            {'conta': '2.1.2.1', 'descricao': 'Fornecedores',       'tipofluxocaixa': 2},
            {'conta': '2.1.2.2', 'descricao': 'Salários',           'tipofluxocaixa': 2},
            {'conta': '2.1.2.3', 'descricao': '13º Salário',        'tipofluxocaixa': 2},
            {'conta': '2.1.2.4', 'descricao': 'Férias',             'tipofluxocaixa': 2},
            {'conta': '2.1.3', 'descricao': 'Empréstimos',           'tipofluxocaixa': 2},
            {'conta': '3',     'descricao': 'Custos',                 'tipofluxocaixa': 2},
            {'conta': '3.1',   'descricao': 'Custos das mercadorias', 'tipofluxocaixa': 2},
            {'conta': '3.1.1', 'descricao': 'Compra de mercadoria','tipofluxocaixa': 2},
            {'conta': '3.1.2', 'descricao': 'Frete',                'tipofluxocaixa': 2},
            {'conta': '3.1.3', 'descricao': 'Mão de obra',          'tipofluxocaixa': 2},
            {'conta': '3.2',   'descricao': 'Custo de Produção',       'tipofluxocaixa': 2},
            {'conta': '3.2.1', 'descricao': 'Matéria-prima',       'tipofluxocaixa': 2},
            {'conta': '3.2.2', 'descricao': 'Material de consumo','tipofluxocaixa': 2},
            {'conta': '3.2.3', 'descricao': 'Combustível',         'tipofluxocaixa': 2},
            {'conta': '3.2.4', 'descricao': 'Mão de obra',         'tipofluxocaixa': 2},
            {'conta': '3.3',   'descricao': 'Custo de prestação de serviço', 'tipofluxocaixa': 2},
            {'conta': '3.3.1', 'descricao': 'Material de uso',      'tipofluxocaixa': 2},
            {'conta': '3.3.2', 'descricao': 'Combustível',         'tipofluxocaixa': 2},
            {'conta': '3.3.3', 'descricao': 'Mão de obra',         'tipofluxocaixa': 2},
            {'conta': '4',     'descricao': 'Despesas',              'tipofluxocaixa': 2},
            {'conta': '4.1',   'descricao': 'Administrativas',        'tipofluxocaixa': 2},
            {'conta': '4.1.1', 'descricao': 'Aluguel',              'tipofluxocaixa': 2},
            {'conta': '4.1.2', 'descricao': 'Energia e Água',        'tipofluxocaixa': 2},
            {'conta': '4.1.3', 'descricao': 'Internet',             'tipofluxocaixa': 2},
            {'conta': '4.1.4', 'descricao': 'Correios',             'tipofluxocaixa': 2},
            {'conta': '4.1.5', 'descricao': 'Honorários',           'tipofluxocaixa': 2},
            {'conta': '4.1.6', 'descricao': 'Serviços terceirizados','tipofluxocaixa': 2},
            {'conta': '4.2',   'descricao': 'Despesas financeiras',  'tipofluxocaixa': 2},
            {'conta': '4.2.1', 'descricao': 'Juros passivos',        'tipofluxocaixa': 2},
            {'conta': '4.2.2', 'descricao': 'Despesas com banco',    'tipofluxocaixa': 2},
            {'conta': '4.2.3', 'descricao': 'Comissões e juros',     'tipofluxocaixa': 2},
            {'conta': '4.2.4', 'descricao': 'Descontos',            'tipofluxocaixa': 2},
            {'conta': '4.3',   'descricao': 'Despesas comerciais',  'tipofluxocaixa': 2},
            {'conta': '4.3.1', 'descricao': 'Publicidade',           'tipofluxocaixa': 2},
            {'conta': '4.3.2', 'descricao': 'Brindes',              'tipofluxocaixa': 2},
            {'conta': '5',     'descricao': 'Receitas',              'tipofluxocaixa': 2},
            {'conta': '5.1',   'descricao': 'Receita de vendas',      'tipofluxocaixa': 2},
            {'conta': '5.1.1', 'descricao': 'Vendas de produtos à vista','tipofluxocaixa': 2},
            {'conta': '5.1.2', 'descricao': 'Vendas de produto a prazo','tipofluxocaixa': 2},
            {'conta': '5.2',   'descricao': 'Receita de prestação de serviço','tipofluxocaixa': 2},
            {'conta': '5.2.1', 'descricao': 'Vendas de produtos à vista','tipofluxocaixa': 2},
            {'conta': '5.2.2', 'descricao': 'Vendas de produto a prazo','tipofluxocaixa': 2},
            {'conta': '5.3',   'descricao': 'Receitas financeiras',    'tipofluxocaixa': 2},
            {'conta': '5.3.1', 'descricao': 'Juros ativos',           'tipofluxocaixa': 2},
            {'conta': '5.3.2', 'descricao': 'Descontos obtidos',      'tipofluxocaixa': 2},
            {'conta': '5.3.3', 'descricao': 'Juros em aplicações financeiras','tipofluxocaixa': 2},
            {'conta': '5.3.4', 'descricao': 'Despesas recuperadas',   'tipofluxocaixa': 2},
        
        ]

        for item in dados:
            # Trunca a descrição para no máximo 30 caracteres
            descricao = item['descricao']
            if descricao and len(descricao) > 30:
                descricao = descricao[:30]
            PlanoDeContas.objects.get_or_create(
                conta=item['conta'],
                tipofluxocaixa=item['tipofluxocaixa'],
                defaults={'descricao': descricao}
            )

        self.stdout.write(self.style.SUCCESS('Plano de contas populado com sucesso!'))
